### and or not

In [ ]:
(10 > 5) or (10 < 5)

True

In [2]:
(10 > 5) and (10 < 5)

False

### List

In [3]:
l = [1, 2, 3, 4, 5]

In [ ]:
l[0]

5

In [6]:
l[-1]

5

In [7]:
len(l)

5

In [8]:
l.append(6)

In [9]:
l[-1]

6

In [10]:
l = [1, 'alo', 3.14, True]

In [11]:
l[0]

1

In [12]:
type(l)

list

In [13]:
type(l[2])

float

In [15]:
print(l[1])

alo

In [16]:
len(l[1])

3

### Tuple

In [17]:
t = (1, 2, 3)

### Set

In [20]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 10, 10, 10, 10]

In [24]:
my_set = set(my_list)
print(my_set)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11}

In [25]:
a = {1, 2, 3, 4, 5}
b = {4, 5, 6, 7, 8}

In [26]:
a.intersection(b)

{4, 5}

### Dictionary

In [ ]:
customers = {
            'Alice': 25,
            'Bob': 30,
            'Charlie': 35
           }

In [28]:
print(customers)

{'Alice': 25, 'Bob': 30, 'Charlie': 35}

In [38]:
customer1 = {'name': 'Alice', 'age': 30, 'email': 'alice@example.com'}
customer1['state'] = 'California'
print(customer1)

{'name': 'Alice', 'age': 30, 'email': 'alice@example.com', 'state': 'California'}

In [35]:
customer2 = {'name': 'Bob', 'age': 25, 'email': 'bob@example.com'}
customer2['state'] = 'Texas'
print(customer2)

{'name': 'Bob', 'age': 25, 'email': 'bob@example.com', 'state': 'Texas'}

In [36]:
customer3 = {'name': 'Charlie', 'age': 35, 'email': 'charlie@example.com'}
customer3['state'] = 'New York'
print(customer3)

{'name': 'Charlie', 'age': 35, 'email': 'charlie@example.com', 'state': 'New York'}

In [39]:
customer_list = [customer1, customer2, customer3]
print(customer_list)

[{'name': 'Alice', 'age': 30, 'email': 'alice@example.com', 'state': 'California'}, {'name': 'Bob', 'age': 25, 'email': 'bob@example.com', 'state': 'Texas'}, {'name': 'Charlie', 'age': 35, 'email': 'charlie@example.com', 'state': 'New York'}]

### pandas

In [ ]:
import pandas as pd

In [41]:
data = {
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [30, 25, 35],
    'email': ['alice@example.com', 'bob@example.com', 'charlie@example.com']
}

In [42]:
data['name']

['Alice', 'Bob', 'Charlie']

In [43]:
data['age']

[30, 25, 35]

In [46]:
df = pd.DataFrame(data)
print(df)

      name  age                email
0    Alice   30    alice@example.com
1      Bob   25      bob@example.com
2  Charlie   35  charlie@example.com

In [47]:
df.head()

      name  age                email
0    Alice   30    alice@example.com
1      Bob   25      bob@example.com
2  Charlie   35  charlie@example.com

In [48]:
type(df)

pandas.DataFrame

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   age     3 non-null      int64
 2   email   3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [52]:
df.shape

(3, 3)

In [54]:
list(df.columns)

['name', 'age', 'email']

In [55]:
list(df.index)

[0, 1, 2]

In [57]:
df.head(2)

    name  age              email
0  Alice   30  alice@example.com
1    Bob   25    bob@example.com

In [59]:
df.head(0)

Empty DataFrame
Columns: [name, age, email]
Index: []

In [60]:
df['name']

0      Alice
1        Bob
2    Charlie
Name: name, dtype: str

In [63]:
df[['name', 'age']]

      name  age
0    Alice   30
1      Bob   25
2  Charlie   35

In [64]:
df['State'] = 'Unknown'

In [65]:
df.head()

      name  age                email    State
0    Alice   30    alice@example.com  Unknown
1      Bob   25      bob@example.com  Unknown
2  Charlie   35  charlie@example.com  Unknown

In [71]:
df['age'] = df['age'] * 0.9
df.head()

      name   age                email    State
0    Alice  27.0    alice@example.com  Unknown
1      Bob  22.5      bob@example.com  Unknown
2  Charlie  31.5  charlie@example.com  Unknown

In [74]:
df['age'] = df['age'] * 0.9
df.head()

      name    age                email    State
0    Alice  24.30    alice@example.com  Unknown
1      Bob  20.25      bob@example.com  Unknown
2  Charlie  28.35  charlie@example.com  Unknown

In [76]:
df['age'] * 0.99

0    24.0570
1    20.0475
2    28.0665
Name: age, dtype: float64

In [77]:
df.drop('State', axis=1, inplace=True)
df.head()

      name    age                email
0    Alice  24.30    alice@example.com
1      Bob  20.25      bob@example.com
2  Charlie  28.35  charlie@example.com

In [78]:
df.loc[df['age'] >= 18, 'status'] = 'Adult'
df.loc[df['age'] < 18, 'status'] = 'Minor'
df.head()

      name    age                email status
0    Alice  24.30    alice@example.com  Adult
1      Bob  20.25      bob@example.com  Adult
2  Charlie  28.35  charlie@example.com  Adult