In [10]:
import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format

## Importing Data

In [3]:
df_orders = pd.read_csv('../data/raw/archive/orders.csv')

print(df_orders.columns)
print(df_orders.shape)
df_orders.head()

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')
(3421083, 7)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [4]:
df_orders_products_train = pd.read_csv('../data/raw/archive/order_products_train.csv')

print(df_orders_products_train.columns)
print(df_orders_products_train.shape)
df_orders_products_train.head()

Index(['order_id', 'product_id', 'add_to_cart_order', 'reordered'], dtype='str')
(1384617, 4)

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [5]:
df_products = pd.read_csv("../data/raw/archive/products.csv")

print(df_products.columns)
print(df_products.shape)
df_products.head()

Index(['product_id', 'product_name', 'aisle_id', 'department_id', 'prices'], dtype='str')
(49693, 5)

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [6]:
df_departments = pd.read_csv('../data/processed/departments_t.csv')

print(df_departments.columns)
print(df_departments.shape)
df_departments.head()

Index(['department_id', 'department'], dtype='str')
(21, 2)

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [7]:
df_aisles = pd.read_csv('../data/raw/archive/aisles.csv')

print(df_aisles.columns)
print(df_aisles.shape)
df_aisles.head()

Index(['aisle_id', 'aisle'], dtype='str')
(134, 2)

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

## Working With `Orders` Table

In [11]:
df_orders.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,"3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,214,874.00"
mean,"1,710,542.00","102,978.21",17.15,2.78,13.45,11.11
std,"987,581.74","59,533.72",17.73,2.05,4.23,9.21
min,1.00,1.00,1.00,0.00,0.00,0.00
25%,"855,271.50","51,394.00",5.00,1.00,10.00,4.00
50%,"1,710,542.00","102,689.00",11.00,3.00,13.00,7.00
75%,"2,565,812.50","154,385.00",23.00,5.00,16.00,15.00
max,"3,421,083.00","206,209.00",100.00,6.00,23.00,30.00

In [13]:
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.00
2,473747,1,prior,3,3,12,21.00
3,2254736,1,prior,4,4,7,29.00
4,431534,1,prior,5,4,15,28.00

In [12]:
df_orders.isna().sum()

order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64

In [ ]:
df_orders['order_id']

np.int64(5851906156986)

In [16]:
df_orders['order_id'].nunique()

3421083

In [18]:
if len(df_orders['order_id']) == df_orders['order_id'].nunique():
    print("No duplicate order_id values found.")

No duplicate order_id values found.

In [19]:
df_orders.shape

(3421083, 7)

In [20]:
if df_orders['order_id'].nunique() == df_orders.shape[0]:
    print("order_id is unique")
else:    
    print("order_id is not unique")

order_id is unique

In [21]:
if df_orders['user_id'].nunique() == df_orders.shape[0]:
    print("user_id is unique")
else:    
    print("user_id is not unique")

user_id is not unique

In [26]:
df_orders['user_id'].nunique()

206209

In [28]:
df_orders['user_id'].nunique() == df_orders.shape[0]

False

In [30]:
df_orders['order_id'].nunique() // df_orders['user_id'].nunique()

16

1

In [36]:
df_orders['eval_set'].value_counts()

eval_set
prior    3214874
train     131209
test       75000
Name: count, dtype: int64

In [39]:
df_orders['order_dow'].value_counts().reset_index().sort_values(by='order_dow')

   order_dow   count
0          0  600905
1          1  587478
2          2  467260
5          3  436972
6          4  426339
3          5  453368
4          6  448761

In [48]:
df_orders['order_hour_of_day'].value_counts().reset_index().sort_values(by='order_hour_of_day')

    order_hour_of_day   count
18                  0   22758
19                  1   12398
21                  2    7539
23                  3    5474
22                  4    5527
20                  5    9569
17                  6   30529
13                  7   91868
10                  8  178201
7                   9  257812
0                  10  288418
1                  11  284728
5                  12  272841
4                  13  277999
3                  14  283042
2                  15  283639
6                  16  272553
8                  17  228795
9                  18  182912
11                 19  140569
12                 20  104292
14                 21   78109
15                 22   61468
16                 23   40043

In [50]:
df_orders['order_hour_of_day'].value_counts().sort_values()

order_hour_of_day
3       5474
4       5527
2       7539
5       9569
1      12398
0      22758
6      30529
23     40043
22     61468
21     78109
7      91868
20    104292
19    140569
8     178201
18    182912
17    228795
9     257812
16    272553
12    272841
13    277999
14    283042
15    283639
11    284728
10    288418
Name: count, dtype: int64

In [ ]:
df_first_orders = df_orders[['days_since_prior_order', 'order_number', 'user_id']][df_orders['order_number'] == 1].reset_index()
df_first_orders.drop(columns='index', inplace=True)
df_first_orders.head()

   days_since_prior_order  order_number  user_id
0                     NaN             1        1
1                     NaN             1        2
2                     NaN             1        3
3                     NaN             1        4
4                     NaN             1        5

In [ ]:
## want to see row number 26
df_orders.iloc[26]

order_id                  1374495
user_id                         3
eval_set                    prior
order_number                    1
order_dow                       1
order_hour_of_day              14
days_since_prior_order        NaN
Name: 26, dtype: object

In [66]:
df_orders['order_dow'].is_unique

False

In [71]:
df_orders['order_dow'].between(0, 6).all()

np.True_

In [72]:
df_orders['order_dow'].between(7, 8).all()

np.False_

In [ ]:
df_order_train = df_orders[df_orders['eval_set'] == 'train']
df_order_train.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
10,1187899,1,train,11,4,8,14.00
25,1492625,2,train,15,1,11,30.00
49,2196797,5,train,5,0,11,6.00
74,525192,7,train,21,2,11,6.00
78,880375,8,train,4,1,14,10.00