# Dates

In [1]:
from datetime import datetime, date, timedelta

In [2]:
my_date = date(2026, 3, 24)

In [4]:
print(my_date)

2026-03-24

In [5]:
type(my_date)

datetime.date

In [7]:
my_time = datetime(2026, 3, 24, 4, 56, 34)

In [8]:
print(my_time)

2026-03-24 04:56:34

In [10]:
today = date.today()
print(today)

2026-04-18

In [12]:
now = datetime.now()
print(now)

2026-04-18 17:42:05.027816

In [15]:
today.year
print(today.year)

2026

In [18]:
my_date.strftime("%Y/%m/%d")

'2026/03/24'

In [19]:
start_date = my_date
end_date = date(2026, 4, 4)

In [20]:
delta = end_date - start_date
print(delta)

11 days, 0:00:00

In [22]:
print(end_date + delta)

2026-04-15

# Dates and Pandas

In [23]:
import pandas as pd

df_dates = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105],
    "signup_date": ["2024-01-15", "2024-02-20", "2024-03-05", "2024-03-18", "2024-04-10"],
    "last_purchase": ["2024-06-01", "2024-06-15", "2024-07-01", "2024-07-08", "2024-07-12"]
})

df_dates

   customer_id signup_date last_purchase
0          101  2024-01-15    2024-06-01
1          102  2024-02-20    2024-06-15
2          103  2024-03-05    2024-07-01
3          104  2024-03-18    2024-07-08
4          105  2024-04-10    2024-07-12

In [24]:
df_dates.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5 non-null      int64
 1   signup_date    5 non-null      str
 2   last_purchase  5 non-null      str
dtypes: int64(1), str(2)
memory usage: 252.0 bytes

In [30]:
df_dates["signup_date"] = pd.to_datetime(df_dates["signup_date"])
df_dates["last_purchase"] = pd.to_datetime(df_dates["last_purchase"])

In [28]:
df_dates.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5 non-null      int64
 1   signup_date    5 non-null      datetime64[us]
 2   last_purchase  5 non-null      datetime64[us]
dtypes: datetime64[us](2), int64(1)
memory usage: 252.0 bytes

In [31]:
df_dates.to_csv('../data/test.csv', index=False)

In [33]:
test = pd.read_csv('../data/test.csv',parse_dates=['signup_date',
                                                   'last_purchase'],
                                                   dtype={'customer_id':str})
test.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5 non-null      str
 1   signup_date    5 non-null      datetime64[us]
 2   last_purchase  5 non-null      datetime64[us]
dtypes: datetime64[us](2), str(1)
memory usage: 252.0 bytes

In [36]:
df_dates["signup_year"] = df_dates["signup_date"].dt.year
df_dates["signup_month"] = df_dates["signup_date"].dt.month
df_dates["signup_day"] = df_dates["signup_date"].dt.day

df_dates

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day
0,101,2024-01-15,2024-06-01,2024,1,15
1,102,2024-02-20,2024-06-15,2024,2,20
2,103,2024-03-05,2024-07-01,2024,3,5
3,104,2024-03-18,2024-07-08,2024,3,18
4,105,2024-04-10,2024-07-12,2024,4,10

In [ ]:
df_dates["signup_month_name"] = df_dates["signup_date"].dt.month_name()
df_dates["signup_day_name"] = df_dates["signup_date"].dt.day_name()

df_dates[["signup_date", "signup_month_name", "signup_day_name"]]

  signup_date signup_month_name signup_day_name
0  2024-01-15           January          Monday
1  2024-02-20          February         Tuesday
2  2024-03-05             March         Tuesday
3  2024-03-18             March          Monday
4  2024-04-10             April       Wednesday

In [38]:
df_dates["signup_quarter"] = df_dates["signup_date"].dt.quarter
df_dates[["signup_date", "signup_quarter"]]

  signup_date  signup_quarter
0  2024-01-15               1
1  2024-02-20               1
2  2024-03-05               1
3  2024-03-18               1
4  2024-04-10               2

In [39]:
df_dates["signup_dow"] = df_dates["signup_date"].dt.dayofweek
df_dates[["signup_date", "signup_dow"]]

  signup_date  signup_dow
0  2024-01-15           0
1  2024-02-20           1
2  2024-03-05           1
3  2024-03-18           0
4  2024-04-10           2

In [40]:
df_dates["is_weekend"] = (df_dates["signup_date"].dt.dayofweek >= 5).astype(int)
df_dates[["signup_date", "signup_dow", "is_weekend"]]

  signup_date  signup_dow  is_weekend
0  2024-01-15           0           0
1  2024-02-20           1           0
2  2024-03-05           1           0
3  2024-03-18           0           0
4  2024-04-10           2           0

In [41]:
df_dates["days_between_signup_and_purchase"] = (
    df_dates["last_purchase"] - df_dates["signup_date"]
).dt.days

df_dates[["signup_date", "last_purchase", "days_between_signup_and_purchase"]]

  signup_date last_purchase  days_between_signup_and_purchase
0  2024-01-15    2024-06-01                               138
1  2024-02-20    2024-06-15                               116
2  2024-03-05    2024-07-01                               118
3  2024-03-18    2024-07-08                               112
4  2024-04-10    2024-07-12                                93

In [42]:
df_dates[df_dates["signup_date"] >= "2024-03-01"]

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,signup_quarter,signup_dow,is_weekend,days_between_signup_and_purchase
2,103,2024-03-05,2024-07-01,2024,3,5,March,Tuesday,1,1,0,118
3,104,2024-03-18,2024-07-08,2024,3,18,March,Monday,1,0,0,112
4,105,2024-04-10,2024-07-12,2024,4,10,April,Wednesday,2,2,0,93

In [43]:
df_dates[df_dates["signup_date"].dt.month == 3]

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,signup_quarter,signup_dow,is_weekend,days_between_signup_and_purchase
2,103,2024-03-05,2024-07-01,2024,3,5,March,Tuesday,1,1,0,118
3,104,2024-03-18,2024-07-08,2024,3,18,March,Monday,1,0,0,112

In [44]:
df_dates[df_dates["signup_date"].dt.year == 2024]

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,signup_quarter,signup_dow,is_weekend,days_between_signup_and_purchase
0,101,2024-01-15,2024-06-01,2024,1,15,January,Monday,1,0,0,138
1,102,2024-02-20,2024-06-15,2024,2,20,February,Tuesday,1,1,0,116
2,103,2024-03-05,2024-07-01,2024,3,5,March,Tuesday,1,1,0,118
3,104,2024-03-18,2024-07-08,2024,3,18,March,Monday,1,0,0,112
4,105,2024-04-10,2024-07-12,2024,4,10,April,Wednesday,2,2,0,93

In [45]:
df_dates.sort_values("signup_date")

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,signup_quarter,signup_dow,is_weekend,days_between_signup_and_purchase
0,101,2024-01-15,2024-06-01,2024,1,15,January,Monday,1,0,0,138
1,102,2024-02-20,2024-06-15,2024,2,20,February,Tuesday,1,1,0,116
2,103,2024-03-05,2024-07-01,2024,3,5,March,Tuesday,1,1,0,118
3,104,2024-03-18,2024-07-08,2024,3,18,March,Monday,1,0,0,112
4,105,2024-04-10,2024-07-12,2024,4,10,April,Wednesday,2,2,0,93

In [46]:
pd.date_range(start="2024-07-01", periods=7, freq="D")

DatetimeIndex(['2024-07-01', '2024-07-02', '2024-07-03', '2024-07-04',
               '2024-07-05', '2024-07-06', '2024-07-07'],
              dtype='datetime64[us]', freq='D')

In [47]:
pd.date_range(start="2024-01-01", periods=6, freq="MS")

DatetimeIndex(['2024-01-01', '2024-02-01', '2024-03-01', '2024-04-01',
               '2024-05-01', '2024-06-01'],
              dtype='datetime64[us]', freq='MS')

In [48]:
import pandas as pd

some_date = pd.Timestamp("2024-07-15")

print(f"Original date: {some_date}")
print(f"Beginning of month: {some_date.to_period('M').start_time}")
print(f"End of month: {some_date.to_period('M').end_time}")

Original date: 2024-07-15 00:00:00
Beginning of month: 2024-07-01 00:00:00
End of month: 2024-07-31 23:59:59.999999

In [49]:
print(f"Beginning of month (date only): {some_date.to_period('M').start_time.date()}")
print(f"End of month (date only): {some_date.to_period('M').end_time.date()}")

Beginning of month (date only): 2024-07-01
End of month (date only): 2024-07-31

In [50]:
df_dates["signup_month"] = df_dates["signup_date"].dt.to_period("M").dt.start_time
df_dates["signup_month"] = df_dates["signup_date"].dt.to_period("M").dt.end_time

df_dates

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,signup_quarter,signup_dow,is_weekend,days_between_signup_and_purchase
0,101,2024-01-15,2024-06-01,2024,2024-01-31 23:59:59.999999,15,January,Monday,1,0,0,138
1,102,2024-02-20,2024-06-15,2024,2024-02-29 23:59:59.999999,20,February,Tuesday,1,1,0,116
2,103,2024-03-05,2024-07-01,2024,2024-03-31 23:59:59.999999,5,March,Tuesday,1,1,0,118
3,104,2024-03-18,2024-07-08,2024,2024-03-31 23:59:59.999999,18,March,Monday,1,0,0,112
4,105,2024-04-10,2024-07-12,2024,2024-04-30 23:59:59.999999,10,April,Wednesday,2,2,0,93

In [51]:
list(pd.date_range(start="2024-07-01", periods=7, freq="MS"))

[Timestamp('2024-07-01 00:00:00'),
 Timestamp('2024-08-01 00:00:00'),
 Timestamp('2024-09-01 00:00:00'),
 Timestamp('2024-10-01 00:00:00'),
 Timestamp('2024-11-01 00:00:00'),
 Timestamp('2024-12-01 00:00:00'),
 Timestamp('2025-01-01 00:00:00')]